name: API Tests

on:
  # 1. Scheduled run - Daily execution (UTC 02:00, Taiwan 10:00)
  schedule:
    - cron: "0 2 * * *"

  # 2. Manual trigger (can run on any branch)
  workflow_dispatch:
    inputs:
      pytest_marks:
        description: 'Pytest marks to run (e.g: smoke, products, "positive")'
        required: false
        default: ""
        type: string
      environment:
        description: "Target environment"
        required: false
        default: "staging"
        type: choice
        options:
          - staging
          - production

# Permissions needed for GitHub Pages deployment
permissions:
  contents: write
  pages: write
  id-token: write
  actions: read

env:
  ENVIRONMENT: production
  BASE_URL: https://fakestoreapi.com
  ALLURE_RESULTS_PATH: allure-results

jobs:
  scheduled-tests:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-env: [production, staging]
        test-suite: [smoke]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display trigger information
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Runner OS: ${{ runner.os }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Scheduled run with matrix:"
          echo "- Environment: ${{ matrix.test-env }}"
          echo "- Test Suite: ${{ matrix.test-suite }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t fakestore-api-tests .
          echo "Docker image built successfully"

      - name: Create reports directory
        run: |
          mkdir -p reports/{allure/{results,reports},html,coverage,logs}
          echo "Reports directory structure created"

      - name: Run API Tests
        env:
          TEST_TYPE: ${{ matrix.test-suite }}
          ENVIRONMENT: ${{ matrix.test-env }}
        run: |
          echo "Running tests with marks: $TEST_TYPE on $ENVIRONMENT environment..."
          docker run --rm \
            -e ENVIRONMENT=$ENVIRONMENT \
            -v $(pwd)/reports:/app/reports \
            fakestore-api-tests pytest -m "$TEST_TYPE" -v --alluredir=/app/reports/allure/results

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.test-env }}-${{ matrix.test-suite }}
          path: reports/allure/results
          retention-days: 30

  manual-tests:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display trigger information
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Runner OS: ${{ runner.os }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Manual run with options:"
          echo "- Pytest marks: ${{ github.event.inputs.pytest_marks }}"
          echo "- Environment: ${{ github.event.inputs.environment }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t fakestore-api-tests .
          echo "Docker image built successfully"

      - name: Create reports directory
        run: |
          mkdir -p reports/{allure/{results,reports},html,coverage,logs}
          echo "Reports directory structure created"

      - name: Run API Tests
        env:
          TEST_TYPE: ${{ github.event.inputs.pytest_marks }}
          ENVIRONMENT: ${{ github.event.inputs.environment }}
        run: |
          echo "Running tests with marks: $TEST_TYPE on $ENVIRONMENT environment..."
          docker run --rm \
            -e ENVIRONMENT=$ENVIRONMENT \
            -v $(pwd)/reports:/app/reports \
            fakestore-api-tests pytest -m "$TEST_TYPE" -v --alluredir=/app/reports/allure/results

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-manual
          path: reports/allure/results
          retention-days: 30

  # Common steps for all jobs
  generate-report:
    needs: [scheduled-tests, manual-tests]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          path: reports/allure/results
          pattern: test-results-*
          merge-multiple: true

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: reports/allure/results
          allure_report: reports/allure/reports
          gh_pages: gh-pages
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: reports/allure/reports
          destination_dir: allure-report/
          keep_files: true
          force_orphan: true
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"

      - name: Create redirect index.html
        run: |
          # Set git user info
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Create and commit index.html
          echo '<!DOCTYPE html>
          <html lang="en">
            <head>
              <meta http-equiv="refresh" content="0; url=allure-report/">
              <title>Redirecting to Allure Report...</title>
            </head>
            <body>
              <p>Redirecting to <a href="allure-report/">Allure Report</a>...</p>
            </body>
          </html>' > index.html
          git add index.html
          git commit -m "chore: add redirect index.html to Allure report"

          # Create or checkout gh-pages branch
          git checkout -b gh-pages || git checkout gh-pages

          # Pull remote changes if they exist
          git pull origin gh-pages || true

          # Force push to update the branch
          git push -f origin gh-pages

      - name: Test Results Summary
        run: |
          echo "## API Test Results Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Trigger**: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Reports" >> $GITHUB_STEP_SUMMARY
          echo "- [Allure Report](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/allure-report/)" >> $GITHUB_STEP_SUMMARY
          echo "- [Test Artifacts](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY

  # Additional parallel job: Generate test insights
  test-insights:
    runs-on: ubuntu-latest
    needs: generate-report
    if: always()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Test Insights
        run: |
          echo "## Test Execution Insights" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Total Workflow Duration**: ${{ github.event.repository.updated_at }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Runner**: ubuntu-latest" >> $GITHUB_STEP_SUMMARY
          echo "- **Docker**: Yes" >> $GITHUB_STEP_SUMMARY
          echo "- **Parallel Execution**: Yes (Matrix Strategy)" >> $GITHUB_STEP_SUMMARY
          echo "- **Report Generation**: Allure + GitHub Pages" >> $GITHUB_STEP_SUMMARY
